name: runnable old node
on: [ push, pull_request ]

jobs:
  runnable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 6, 7, 8, 9, 10.x, 11.x, 12.x, 13.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run with CommonJS
        run: node example/commonjs.js
